M48
; DRILL file {KiCad (6.0.6)} date Thu Aug  3 10:40:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-03T10:40:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.6491Y-2.7012
X1.582Y-0.8
X1.9Y-4.1
X3.1Y-2.7
T0
M30
